---
- block:
  - name: Install support packages
    package:
      name: "{{ wg_node_packages | join(',') }}"
      state: latest
    async: 3600
    poll: 30
    register: result
    until: result is succeeded

  rescue:
  - name: Package install failure message
    fail:
      msg: >
        Unable to install {{ wg_node_packages | join(', ') }}.
        Please ensure repos are configured properly to provide these packages
        and indicated versions.
